// Animate UI Icons Hub - https://animate-ui.com/
'use client';

export * from './icon';

export { Activity, Activity as ActivityIcon } from './activity';
export { AlertCircle, AlertCircle as AlertCircleIcon } from './alert-circle';
export { ArrowDown, ArrowDown as ArrowDownIcon } from './arrow-down';
export { ArrowLeft, ArrowLeft as ArrowLeftIcon } from './arrow-left';
export { ArrowRight, ArrowRight as ArrowRightIcon } from './arrow-right';
export { ArrowUp, ArrowUp as ArrowUpIcon } from './arrow-up';
export { BellRing, BellRing as BellRingIcon } from './bell-ring';
export { Bell, Bell as BellIcon } from './bell';
export { Calendar, Calendar as CalendarIcon } from './calendar';
export { ChartBar, ChartBar as ChartBarIcon } from './chart-bar';
export { ChartColumn, ChartColumn as ChartColumnIcon } from './chart-column';
export { ChartLine, ChartLine as ChartLineIcon } from './chart-line';
export { ChartSpline, ChartSpline as ChartSplineIcon } from './chart-spline';
export { CheckCheck, CheckCheck as CheckCheckIcon } from './check-check';
export { Check, Check as CheckIcon } from './check';
export { ChevronDown, ChevronDown as ChevronDownIcon } from './chevron-down';
export { ChevronLeft, ChevronLeft as ChevronLeftIcon } from './chevron-left';
export { ChevronRight, ChevronRight as ChevronRightIcon } from './chevron-right';
export { ChevronUp, ChevronUp as ChevronUpIcon } from './chevron-up';
export { CircleCheckBig, CircleCheckBig as CircleCheckBigIcon } from './circle-check-big';
export { CircleCheck, CircleCheck as CircleCheckIcon } from './circle-check';
export { CirclePlus, CirclePlus as CirclePlusIcon } from './circle-plus';
export { CircleX, CircleX as CircleXIcon } from './circle-x';
export { ClipboardCheck, ClipboardCheck as ClipboardCheckIcon } from './clipboard-check';
export { ClipboardList, ClipboardList as ClipboardListIcon } from './clipboard-list';
export { Clipboard, Clipboard as ClipboardIcon } from './clipboard';
export { Clock, Clock as ClockIcon } from './clock';
export { Cog, Cog as CogIcon } from './cog';
export { Copy, Copy as CopyIcon } from './copy';
export { CreditCard, CreditCard as CreditCardIcon } from './credit-card';
export { DollarSign, DollarSign as DollarSignIcon } from './dollar-sign';
export { Download, Download as DownloadIcon } from './download';
export { Edit, Edit as EditIcon, Edit as FiEdit2 } from './edit';
export { ExternalLink, ExternalLink as ExternalLinkIcon } from './external-link';
export { EyeOff, EyeOff as EyeOffIcon } from './eye-off';
export { Eye, Eye as EyeIcon } from './eye';
export { Facebook, Facebook as FacebookIcon } from './facebook';
export { FileText, FileText as FileTextIcon } from './file-text';
export { Filter, Filter as FilterIcon } from './filter';
export { Folder, Folder as FolderIcon } from './folder';
export { Forklift, Forklift as ForkliftIcon } from './forklift';
export { Gauge, Gauge as GaugeIcon } from './gauge';
export { Heart, Heart as HeartIcon } from './heart';
export { LayoutDashboard, LayoutDashboard as LayoutDashboardIcon } from './layout-dashboard';
export { List, List as ListIcon } from './list';
export { LoaderCircle, LoaderCircle as LoaderCircleIcon } from './loader-circle';
export { Loader, Loader as LoaderIcon } from './loader';
export { LockOpen, LockOpen as LockOpenIcon } from './lock-open';
export { Lock, Lock as LockIcon } from './lock';
export { LogIn, LogIn as LogInIcon } from './log-in';
export { LogOut, LogOut as LogOutIcon } from './log-out';
export { Mail, Mail as MailIcon } from './mail';
export { MapPin, MapPin as MapPinIcon } from './map-pin';
export { Menu, Menu as MenuIcon } from './menu';
export { MessageCircle, MessageCircle as MessageCircleIcon } from './message-circle';
export { MessageSquareText, MessageSquareText as MessageSquareTextIcon } from './message-square-text';
export { MessageSquare, MessageSquare as MessageSquareIcon } from './message-square';
export { Minus, Minus as MinusIcon } from './minus';
export { Moon, Moon as MoonIcon } from './moon';
export { Package, Package as PackageIcon } from './package';
export { PartyPopper, PartyPopper as PartyPopperIcon } from './party-popper';
export { PhoneCall, PhoneCall as PhoneCallIcon } from './phone-call';
export { Phone, Phone as PhoneIcon } from './phone';
export { Pin, Pin as PinIcon } from './pin';
export { Plus, Plus as PlusIcon } from './plus';
export { RefreshCw, RefreshCw as RefreshCwIcon } from './refresh-cw';
export { RotateCcw, RotateCcw as RotateCcwIcon } from './rotate-ccw';
export { Save, Save as SaveIcon } from './save';
export { Search, Search as SearchIcon } from './search';
export { SendHorizontal, SendHorizontal as SendHorizontalIcon } from './send-horizontal';
export { Send, Send as SendIcon } from './send';
export { Settings, Settings as SettingsIcon } from './settings';
export { ShieldCheck, ShieldCheck as ShieldCheckIcon } from './shield-check';
export { Shield, Shield as ShieldIcon } from './shield';
export { ShoppingCart, ShoppingCart as ShoppingCartIcon } from './shopping-cart';
export { SlidersHorizontal, SlidersHorizontal as SlidersHorizontalIcon } from './sliders-horizontal';
export { SlidersVertical, SlidersVertical as SlidersVerticalIcon } from './sliders-vertical';
export { Sparkle, Sparkle as SparkleIcon } from './sparkle';
export { Sparkles, Sparkles as SparklesIcon } from './sparkles';
export { SquarePlus, SquarePlus as SquarePlusIcon } from './square-plus';
export { SquareX, SquareX as SquareXIcon } from './square-x';
export { Star, Star as StarIcon } from './star';
export { Sun, Sun as SunIcon } from './sun';
export { Timer, Timer as TimerIcon } from './timer';
export { Trash2, Trash2 as Trash2Icon } from './trash-2';
export { Trash, Trash as TrashIcon } from './trash';
export { TrendingDown, TrendingDown as TrendingDownIcon } from './trending-down';
export { TrendingUp, TrendingUp as TrendingUpIcon } from './trending-up';
export { Truck, Truck as TruckIcon } from './truck';
export { Upload, Upload as UploadIcon } from './upload';
export { UserRound, UserRound as UserRoundIcon } from './user-round';
export { User, User as UserIcon } from './user';
export { UsersRound, UsersRound as UsersRoundIcon } from './users-round';
export { Users, Users as UsersIcon } from './users';
export { X, X as XIcon } from './x';
export { Youtube, Youtube as YoutubeIcon } from './youtube';

// Aliases & conveniences for smooth replacement
export { Check as FiCheck } from './check';
export { CircleCheck as FiCheckCircle, CircleCheck as CheckCircle } from './circle-check';
export { CircleCheckBig as CheckCircle2 } from './circle-check-big';
export { CircleX as FiXCircle } from './circle-x';
export { Trash2 as FiTrash2 } from './trash-2';
export { Trash as FiTrash } from './trash';
export { ArrowRight as FiArrowRight } from './arrow-right';
export { ArrowLeft as FiArrowLeft } from './arrow-left';
export { Search as FiSearch } from './search';
export { Menu as FiMenu } from './menu';
export { X as FiX } from './x';
export { Plus as FiPlus } from './plus';
export { CirclePlus as FiPlusCircle } from './circle-plus';
export { Minus as FiMinus, Minus as FiMinusCircle } from './minus';
export { Lock as FiLock } from './lock';
export { Settings as FiSettings } from './settings';
export { Download as FiDownload } from './download';
export { Upload as FiUpload, Upload as FiUploadCloud } from './upload';
export { Sparkles as FiImage } from './sparkles';
export { User as FiUser } from './user';
export { Users as FiUsers } from './users';
export { LogIn as FiLogIn } from './log-in';
export { LogOut as FiLogOut } from './log-out';
export { Bell as FiBell } from './bell';
export { Activity as FiActivity } from './activity';
export { Star as FiStar } from './star';
export { Copy as FiCopy } from './copy';
export { RefreshCw as FiRefreshCw } from './refresh-cw';
export { PhoneCall as FiPhoneCall } from './phone-call';
export { MapPin as FiMapPin } from './map-pin';
export { Clock as FiClock } from './clock';
export { ExternalLink as FiExternalLink, ExternalLink as FiGlobe } from './external-link';
export { LayoutDashboard as FiLayoutDashboard, LayoutDashboard as FiGrid } from './layout-dashboard';
export { Folder as FiFolder, Folder as FiTag, Folder as FiLayers } from './folder';
export { SlidersHorizontal as FiSliders } from './sliders-horizontal';
export { ChartBar as FiBarChart2 } from './chart-bar';
export { ChartColumn as FiPieChart } from './chart-column';
export { Package as FiPackage, Package as FiBox } from './package';
export { ShoppingCart as FiShoppingCart, ShoppingCart as FiShoppingBag } from './shopping-cart';
export { Shield as FiShield } from './shield';
export { ShieldCheck as FiShieldCheck } from './shield-check';
export { CreditCard as FiCreditCard } from './credit-card';
export { Truck as FiTruck } from './truck';
export { TrendingUp as FiTrendingUp } from './trending-up';
export { TrendingDown as FiTrendingDown } from './trending-down';
export { DollarSign as FiDollarSign } from './dollar-sign';
export { Calendar as FiCalendar } from './calendar';
export { Eye as FiEye } from './eye';
export { EyeOff as FiEyeOff } from './eye-off';
export { FileText as FiFileText, FileText as FiPrinter } from './file-text';
export { Edit as FiEdit } from './edit';
export { Filter as FiFilter } from './filter';
export { Mail as FiMail } from './mail';
export { Phone as FiPhone } from './phone';
export { Save as FiSave } from './save';
export { AlertCircle as FiAlertCircle, AlertCircle as FiAlertTriangle } from './alert-circle';
export { Facebook as FiFacebook } from './facebook';
export { Youtube as FiYoutube } from './youtube';
